// packages/solid/src/components/ui/grid.tsx
import { type ComponentProps, splitProps } from "solid-js"
import { cn } from "@/lib/utils"

export interface GridProps extends ComponentProps<"div"> {
  columns?: number
  gap?: number | string
}

export function Grid(props: GridProps) {
  const [local, rest] = splitProps(props, ["class", "columns", "gap", "style", "children"])

  const columns = () => local.columns ?? 1
  const gap = () => {
    if (local.gap === undefined) return undefined
    return typeof local.gap === "number" ? `${local.gap * 0.25}rem` : local.gap
  }

  const customStyle = () => {
    const style: Record<string, string> = {
      "grid-template-columns": `repeat(${columns()}, minmax(0, 1fr))`,
    }
    const gapValue = gap()
    if (gapValue) {
      style.gap = gapValue
    }
    return style
  }

  return (
    <div class={cn("grid", local.class)} style={customStyle()} {...rest}>
      {local.children}
    </div>
  )
}

// packages/react/src/components/ui/grid.tsx
import { type ComponentProps, type CSSProperties } from "react"
import { cn } from "@/lib/utils"

export interface GridProps extends ComponentProps<"div"> {
  columns?: number
  gap?: number | string
}

export function Grid({ className, columns = 1, gap, style, children, ...props }: GridProps) {
  const gridStyle: CSSProperties = {
    display: "grid",
    gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`,
    gap: typeof gap === "number" ? `${gap * 0.25}rem` : gap,
    ...style,
  }

  return (
    <div className={cn(className)} style={gridStyle} {...props}>
      {children}
    </div>
  )
}
