// packages/solid/src/components/ui/skeleton.tsx
import { cva, type VariantProps } from "class-variance-authority"
import { type ComponentProps, splitProps } from "solid-js"
import { cn } from "@/lib/utils"

const skeletonVariants = cva("animate-pulse rounded-md bg-muted", {
  variants: {
    variant: {
      default: "",
      circular: "rounded-full",
    },
  },
  defaultVariants: {
    variant: "default",
  },
})

export interface SkeletonProps extends ComponentProps<"div">, VariantProps<typeof skeletonVariants> {}

export const Skeleton = (props: SkeletonProps) => {
  const [local, rest] = splitProps(props, ["class", "variant"])

  return <div class={cn(skeletonVariants({ variant: local.variant }), local.class)} {...rest} />
}

export { skeletonVariants }

// packages/react/src/components/ui/skeleton.tsx
import { cva, type VariantProps } from "class-variance-authority"
import { type ComponentProps, forwardRef } from "react"
import { cn } from "@/lib/utils"

const skeletonVariants = cva("animate-pulse rounded-md bg-muted", {
  variants: {
    variant: {
      default: "",
      circular: "rounded-full",
    },
  },
  defaultVariants: {
    variant: "default",
  },
})

export interface SkeletonProps extends ComponentProps<"div">, VariantProps<typeof skeletonVariants> {}

const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(
  ({ className, variant, ...props }, ref) => {
    return <div ref={ref} className={cn(skeletonVariants({ variant }), className)} {...props} />
  },
)
Skeleton.displayName = "Skeleton"

export { Skeleton, skeletonVariants }
